/* 20230907: MPC user replication update script
 * adds new columns to table 'mpc_orbits' */
 
alter table mpc_orbits add column if not exists orbit_type_int	int4	;
alter table mpc_orbits add column if not exists u_param	int4	;
alter table mpc_orbits add column if not exists nopp	int4	;
alter table mpc_orbits add column if not exists arc_length_total	double precision	;
alter table mpc_orbits add column if not exists arc_length_sel	double precision	;
alter table mpc_orbits add column if not exists nobs_total	int4	;
alter table mpc_orbits add column if not exists nobs_total_sel	int4	;
alter table mpc_orbits add column if not exists a	double precision	;
alter table mpc_orbits add column if not exists q	double precision	;
alter table mpc_orbits add column if not exists e	double precision	;
alter table mpc_orbits add column if not exists i	double precision	;
alter table mpc_orbits add column if not exists node	double precision	;
alter table mpc_orbits add column if not exists argperi	double precision	;
alter table mpc_orbits add column if not exists peri_time	double precision	;
alter table mpc_orbits add column if not exists yarkovsky	double precision	;
alter table mpc_orbits add column if not exists srp	double precision	;
alter table mpc_orbits add column if not exists A1	double precision	;
alter table mpc_orbits add column if not exists A2	double precision	;
alter table mpc_orbits add column if not exists A3	double precision	;
alter table mpc_orbits add column if not exists DT	double precision	;
alter table mpc_orbits add column if not exists mean_anomaly	double precision	;
alter table mpc_orbits add column if not exists period	double precision	;
alter table mpc_orbits add column if not exists mean_motion	double precision	;
alter table mpc_orbits add column if not exists a_unc	double precision	;
alter table mpc_orbits add column if not exists q_unc	double precision	;
alter table mpc_orbits add column if not exists e_unc	double precision	;
alter table mpc_orbits add column if not exists i_unc	double precision	;
alter table mpc_orbits add column if not exists node_unc	double precision	;
alter table mpc_orbits add column if not exists argperi_unc	double precision	;
alter table mpc_orbits add column if not exists peri_time_unc	double precision	;
alter table mpc_orbits add column if not exists yarkovsky_unc	double precision	;
alter table mpc_orbits add column if not exists srp_unc	double precision	;
alter table mpc_orbits add column if not exists A1_unc	double precision	;
alter table mpc_orbits add column if not exists A2_unc	double precision	;
alter table mpc_orbits add column if not exists A3_unc	double precision	;
alter table mpc_orbits add column if not exists DT_unc	double precision	;
alter table mpc_orbits add column if not exists mean_anomaly_unc	double precision	;
alter table mpc_orbits add column if not exists period_unc	double precision	;
alter table mpc_orbits add column if not exists mean_motion_unc	double precision	;
alter table mpc_orbits add column if not exists Epoch_MJD	double precision	;
alter table mpc_orbits add column if not exists H	double precision	;
alter table mpc_orbits add column if not exists G	double precision	;
alter table mpc_orbits add column if not exists not_normalized_rms	double precision	;
alter table mpc_orbits add column if not exists normalized_rms	double precision	;
alter table mpc_orbits add column if not exists Earth_MOID	double precision	;
alter table mpc_orbits add column if not exists fitting_datetime	timestamp(6);

/* add comments to the new 'mpc_orbits' columns */
 
comment on column mpc_orbits.orbit_type_int	IS	'Orbit Type (Integer)';
comment on column mpc_orbits.u_param	IS	'U parameter';
comment on column mpc_orbits.nopp	IS	'number of oppositions';
comment on column mpc_orbits.arc_length_total	IS	'Arc length over total observations [days]';
comment on column mpc_orbits.arc_length_sel	IS	'Arc length over total observations *selected* [days]';
comment on column mpc_orbits.nobs_total	IS	'Total number of all observations (optical + radar) available';
comment on column mpc_orbits.nobs_total_sel	IS	'Total number of all observations (optical + radar) selected for use in orbit fitting';
comment on column mpc_orbits.a	IS	'Semi Major Axis [au]';
comment on column mpc_orbits.q	IS	'Pericenter Distance [au]';
comment on column mpc_orbits.e	IS	'Eccentricity [au]';
comment on column mpc_orbits.i	IS	'Inclination [degrees]';
comment on column mpc_orbits.node	IS	'Longitude of Ascending Node [degrees]';
comment on column mpc_orbits.argperi	IS	'Argument of Pericenter [degrees]';
comment on column mpc_orbits.peri_time	IS	'Time from Pericenter Passage [days]';
comment on column mpc_orbits.yarkovsky	IS	'Yarkovsky Component ["10^(-10)*au/day^2"]';
comment on column mpc_orbits.srp	IS	'Solar-Radiation Pressure Component ["m^2/ton"]';
comment on column mpc_orbits.A1	IS	'A1 non-grav components ["m^2/ton"]';
comment on column mpc_orbits.A2	IS	'A2 non-grav components ["m^2/ton"]';
comment on column mpc_orbits.A3	IS	'A3 non-grav components ["m^2/ton"]';
comment on column mpc_orbits.DT	IS	'DT non-grav component';
comment on column mpc_orbits.mean_anomaly	IS	'Mean Anomaly [degrees]';
comment on column mpc_orbits.period	IS	'Orbital Period [days]';
comment on column mpc_orbits.mean_motion	IS	'Orbital Mean Motion [degrees per day]';
comment on column mpc_orbits.a_unc	IS	'Uncertainty on Semi Major Axis [au]';
comment on column mpc_orbits.q_unc	IS	'Uncertainty on Pericenter Distance [au]';
comment on column mpc_orbits.e_unc	IS	'Uncertainty on Eccentricity [au]';
comment on column mpc_orbits.i_unc	IS	'Uncertainty on Inclination [degrees]';
comment on column mpc_orbits.node_unc	IS	'Uncertainty on Longitude of Ascending Node [degrees]';
comment on column mpc_orbits.argperi_unc	IS	'Uncertainty on Argument of Pericenter [degrees]';
comment on column mpc_orbits.peri_time_unc	IS	'Uncertainty on Time from Pericenter Passage [days]';
comment on column mpc_orbits.yarkovsky_unc	IS	'Uncertainty on Yarkovsky Component ["10^(-10)*au/day^2"]';
comment on column mpc_orbits.srp_unc	IS	'Uncertainty on Solar-Radiation Pressure Component ["m^2/ton"]';
comment on column mpc_orbits.A1_unc	IS	'Uncertainty on A1 non-grav components ["m^2/ton"]';
comment on column mpc_orbits.A2_unc	IS	'Uncertainty on A2 non-grav components ["m^2/ton"]';
comment on column mpc_orbits.A3_unc	IS	'Uncertainty on A3 non-grav components ["m^2/ton"]';
comment on column mpc_orbits.DT_unc	IS	'Uncertainty on DT non-grav component';
comment on column mpc_orbits.mean_anomaly_unc	IS	'Uncertainty on Mean Anomaly [degrees]';
comment on column mpc_orbits.period_unc	IS	'Uncertainty on Orbital Period [days]';
comment on column mpc_orbits.mean_motion_unc	IS	'Uncertainty on Orbital Mean Motion [degrees per day]';
comment on column mpc_orbits.Epoch_MJD	IS	'Epoch of the Orbfit-Solution in MJD';
comment on column mpc_orbits.H	IS	'H-Magnitude';
comment on column mpc_orbits.G	IS	'G-Slope Parameter';
comment on column mpc_orbits.not_normalized_rms	IS	'unnormalized rms of the fit [arcsec]';
comment on column mpc_orbits.normalized_rms	IS	'rms of the fit [unitless]';
comment on column mpc_orbits.Earth_MOID	IS	'Minimum Orbit Intersection Distance [au] with respect to the Earths Orbit';
comment on column mpc_orbits.fitting_datetime	IS	'Date of the last orbit fit';