apiVersion: v1
kind: Service
metadata:
  labels:
    cnpg.io/cluster: mpcorb
  annotations:
    metallb.universe.tf/address-pool: sdf-dmz
  name: cnpg-load-balancer-gcp-access
  namespace: mpcorb-replica
spec:
  loadBalancerSourceRanges:
    - 34.19.55.28/32
    - 34.28.185.156/32
    - 35.225.165.2/32
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    postgresql: mpcorb
  sessionAffinity: None
  type: LoadBalancer
