/*
 
 Source Server Type    : PostgreSQL
 Source Server Version : 170004 (170004)
 Source Host           : mpc-sbn-db:5432
 Source Catalog        : mpc_sbn
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 170004 (170004)
 File Encoding         : 65001

 Date: 08/04/2025 10:41:20
*/


-- ----------------------------
-- Table structure for obs_sbn
-- ----------------------------
DROP TABLE IF EXISTS "public"."obs_sbn";
CREATE TABLE "public"."obs_sbn" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "trksub" text COLLATE "pg_catalog"."default",
  "trkid" text COLLATE "pg_catalog"."default",
  "obsid" text COLLATE "pg_catalog"."default",
  "submission_id" text COLLATE "pg_catalog"."default",
  "submission_block_id" text COLLATE "pg_catalog"."default",
  "obs80" text COLLATE "pg_catalog"."default",
  "status" char(1) COLLATE "pg_catalog"."default",
  "ref" text COLLATE "pg_catalog"."default",
  "healpix" int8,
  "permid" text COLLATE "pg_catalog"."default",
  "provid" text COLLATE "pg_catalog"."default",
  "artsat" text COLLATE "pg_catalog"."default",
  "mode" text COLLATE "pg_catalog"."default",
  "stn" text COLLATE "pg_catalog"."default",
  "trx" text COLLATE "pg_catalog"."default",
  "rcv" text COLLATE "pg_catalog"."default",
  "sys" text COLLATE "pg_catalog"."default",
  "ctr" int4,
  "pos1" numeric,
  "pos2" numeric,
  "pos3" numeric,
  "poscov11" numeric,
  "poscov12" numeric,
  "poscov13" numeric,
  "poscov22" numeric,
  "poscov23" numeric,
  "poscov33" numeric,
  "prog" text COLLATE "pg_catalog"."default",
  "obstime" timestamp(6),
  "ra" numeric,
  "dec" numeric,
  "rastar" numeric,
  "decstar" numeric,
  "obscenter" text COLLATE "pg_catalog"."default",
  "deltara" numeric,
  "deltadec" numeric,
  "dist" numeric,
  "pa" numeric,
  "rmsra" numeric,
  "rmsdec" numeric,
  "rmsdist" numeric,
  "rmspa" numeric,
  "rmscorr" numeric,
  "delay" numeric,
  "rmsdelay" numeric,
  "doppler" numeric,
  "rmsdoppler" numeric,
  "astcat" text COLLATE "pg_catalog"."default",
  "mag" numeric,
  "rmsmag" numeric,
  "band" text COLLATE "pg_catalog"."default",
  "photcat" text COLLATE "pg_catalog"."default",
  "photap" numeric,
  "nucmag" int2,
  "logsnr" numeric,
  "seeing" numeric,
  "exp" numeric,
  "rmsfit" numeric,
  "com" int2,
  "frq" numeric,
  "disc" char(1) COLLATE "pg_catalog"."default",
  "subfrm" text COLLATE "pg_catalog"."default",
  "subfmt" text COLLATE "pg_catalog"."default",
  "prectime" int4,
  "precra" numeric,
  "precdec" numeric,
  "unctime" numeric,
  "notes" text COLLATE "pg_catalog"."default",
  "remarks" text COLLATE "pg_catalog"."default",
  "deprecated" char(1) COLLATE "pg_catalog"."default",
  "localuse" text COLLATE "pg_catalog"."default",
  "nstars" int4,
  "prev_desig" text COLLATE "pg_catalog"."default",
  "prev_ref" text COLLATE "pg_catalog"."default",
  "rmstime" numeric,
  "created_at" timestamptz(6) DEFAULT now(),
  "updated_at" timestamptz(6) DEFAULT now(),
  "trkmpc" text COLLATE "pg_catalog"."default",
  "orbit_id" text COLLATE "pg_catalog"."default",
  "designation_asterisk" bool,
  "all_pub_ref" text[] COLLATE "pg_catalog"."default",
  "shapeocc" bool,
  "obssubid" text COLLATE "pg_catalog"."default",
  "replacesobsid" text COLLATE "pg_catalog"."default",
  "group_id" text COLLATE "pg_catalog"."default"
)
WITH (fillfactor=85)
;
ALTER TABLE "public"."obs_sbn" OWNER TO "postgres";
COMMENT ON COLUMN "public"."obs_sbn"."id" IS 'MPC_ops: PostgreSQL automatically generated identifier';
COMMENT ON COLUMN "public"."obs_sbn"."trksub" IS 'ADES: Observer-assigned object identifier, unique within a submission batch';
COMMENT ON COLUMN "public"."obs_sbn"."trkid" IS 'ADES: Globally unique tracklet identifier assigned by the MPC';
COMMENT ON COLUMN "public"."obs_sbn"."obsid" IS 'ADES: Globally unique observation identifier assigned by the MPC';
COMMENT ON COLUMN "public"."obs_sbn"."submission_id" IS 'MPC_ops: Unique MPC-assigned submission ID';
COMMENT ON COLUMN "public"."obs_sbn"."submission_block_id" IS 'MPC_ops: Unique MPC-assigned submission block ID';
COMMENT ON COLUMN "public"."obs_sbn"."obs80" IS 'MPC_ops: 80 or 160-Character observation string';
COMMENT ON COLUMN "public"."obs_sbn"."status" IS 'MPC_ops: processing status. Allowed values are: P for ufficially published in a circular (DOU, mid-month, monthly), p for accepted and waiting for publication in the next circular, I for ITF observations';
COMMENT ON COLUMN "public"."obs_sbn"."ref" IS 'ADES: Standard reference field used for citations';
COMMENT ON COLUMN "public"."obs_sbn"."healpix" IS 'MPC_ops: A convenience calculation that maps the observed (Ra,Dec) to a healpix (healpix.sourceforge.io) patch of the sky indicated by the recorded integer. The chosen mapping assumes nside = 32768 & nested = True (see https://astropy-healpix.readthedocs.io/en/latest/coordinates.html), corresponding to a pixel scale of approx 6.4 arcsec.';
COMMENT ON COLUMN "public"."obs_sbn"."permid" IS 'ADES: IAU permanent designation (e.g. the IAU number for a numbered minor planet)';
COMMENT ON COLUMN "public"."obs_sbn"."provid" IS 'ADES: unpacked MPC assigned provisional designation (for more information see https://minorplanetcenter.net/mpcops/documentation/provisional-designation-definition/)';
COMMENT ON COLUMN "public"."obs_sbn"."artsat" IS 'ADES: Artificial satellite identifier';
COMMENT ON COLUMN "public"."obs_sbn"."mode" IS 'ADES: mode of instrumentation (for the documentation on valid values, see https://minorplanetcenter.net/mpcops/documentation/valid-ades-values/#mode)';
COMMENT ON COLUMN "public"."obs_sbn"."stn" IS 'ADES: Observatory code assigned by the MPC for ground-based or spaced-based stations (for the documentation on valid values, see https://minorplanetcenter.net/mpcops/documentation/valid-ades-values/#stn)';
COMMENT ON COLUMN "public"."obs_sbn"."trx" IS 'ADES: Station codes of transmitting antenna for radar observations';
COMMENT ON COLUMN "public"."obs_sbn"."rcv" IS 'ADES: Station codes of receiving antenna for radar observations';
COMMENT ON COLUMN "public"."obs_sbn"."sys" IS 'ADES: Coordinate frame for roving or space-based station coordinates (for the documentation on valid values, see https://minorplanetcenter.net/mpcops/documentation/valid-ades-values/#sys)';
COMMENT ON COLUMN "public"."obs_sbn"."ctr" IS 'ADES: Origin of the reference system given by the coordinate frame (sys). Use public SPICE codes for possible values (https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/C/req/naif_ids.html), e.g. 399=geocenter';
COMMENT ON COLUMN "public"."obs_sbn"."pos1" IS 'ADES: Position of the observer (see https://github.com/IAU-ADES/ADES-Master/blob/master/ADES_Description.pdf)';
COMMENT ON COLUMN "public"."obs_sbn"."pos2" IS 'ADES: Position of the observer (see https://github.com/IAU-ADES/ADES-Master/blob/master/ADES_Description.pdf)';
COMMENT ON COLUMN "public"."obs_sbn"."pos3" IS 'ADES: Position of the observer (see https://github.com/IAU-ADES/ADES-Master/blob/master/ADES_Description.pdf)';
COMMENT ON COLUMN "public"."obs_sbn"."poscov11" IS 'ADES: Element (1,1) of the upper triangular part of the covariance matrix for the observer position in the same units of position coordinates. Missing fields are presumed zero.';
COMMENT ON COLUMN "public"."obs_sbn"."poscov12" IS 'ADES: Element (1,2) of the upper triangular part of the covariance matrix for the observer position in the same units of position coordinates. Missing fields are presumed zero.';
COMMENT ON COLUMN "public"."obs_sbn"."poscov13" IS 'ADES: Element (1,3) of the upper triangular part of the covariance matrix for the observer position in the same units of position coordinates. Missing fields are presumed zero.';
COMMENT ON COLUMN "public"."obs_sbn"."poscov22" IS 'ADES: Element (2,2) of the upper triangular part of the covariance matrix for the observer position in the same units of position coordinates. Missing fields are presumed zero.';
COMMENT ON COLUMN "public"."obs_sbn"."poscov23" IS 'ADES: Element (2,3) of the upper triangular part of the covariance matrix for the observer position in the same units of position coordinates. Missing fields are presumed zero.';
COMMENT ON COLUMN "public"."obs_sbn"."poscov33" IS 'ADES: Element (3,3) of the upper triangular part of the covariance matrix for the observer position in the same units of position coordinates. Missing fields are presumed zero.';
COMMENT ON COLUMN "public"."obs_sbn"."prog" IS 'ADES: Program code assigned by the MPC';
COMMENT ON COLUMN "public"."obs_sbn"."obstime" IS 'ADES: UTC date and time of the observation. ';
COMMENT ON COLUMN "public"."obs_sbn"."ra" IS 'ADES: Right Ascension is decimal degrees in J2000.0 reference frame';
COMMENT ON COLUMN "public"."obs_sbn"."dec" IS 'ADES: Declination is decimal degrees in J2000.0 reference frame';
COMMENT ON COLUMN "public"."obs_sbn"."rastar" IS 'ADES: For occultation, only when stn=244, Right Ascension in the J2000.0 reference frame in decimal degress of the occulted star.';
COMMENT ON COLUMN "public"."obs_sbn"."decstar" IS 'ADES: For occultation, only when stn=244, Declination in the J2000.0 reference frame in decimal degress of the occulted star.';
COMMENT ON COLUMN "public"."obs_sbn"."obscenter" IS 'ADES: Origin of offset observations (full name of a planet or permID or provID for a small body)';
COMMENT ON COLUMN "public"."obs_sbn"."deltara" IS 'ADES: Measured DeltaRA*cos(Dec) in arcsec in the J2000.0 reference frame for offset measurements of a satellite with respect to osbCenter, or for occultation observations with respect to the star (stn=244)';
COMMENT ON COLUMN "public"."obs_sbn"."deltadec" IS 'ADES: Measured DeltaDec in arcsec in the J2000.0 reference frame for offset measurements of a satellite with respect to osbCenter, or for occultation observations with respect to the star (only if stn=244)';
COMMENT ON COLUMN "public"."obs_sbn"."dist" IS 'ADES: Measured distance in arcsec in degrees in the J2000.0 reference frame for offset measurements of a satellite wrt obsCenter, or for occultation observations wrt the star (only if stn=244)';
COMMENT ON COLUMN "public"."obs_sbn"."pa" IS 'ADES: Measured Position Angle in arcsec in degrees in the J2000.0 reference frame for offset measurements of a satellite wrt obsCenter, or for occultation observations wrt the star (only if stn=244)';
COMMENT ON COLUMN "public"."obs_sbn"."rmsra" IS 'ADES: Random component of the RA*cos(Dec) uncertainty in arcsec as estimated by the observer ';
COMMENT ON COLUMN "public"."obs_sbn"."rmsdec" IS 'ADES: Random component of the Dec uncertainty in arcsec as estimated by the observer ';
COMMENT ON COLUMN "public"."obs_sbn"."rmsdist" IS 'ADES: Random component of the distance uncertainty in arcsec as estimated by the observer ';
COMMENT ON COLUMN "public"."obs_sbn"."rmspa" IS 'ADES: Random component of the position angle uncertainty in arcsec as estimated by the observer ';
COMMENT ON COLUMN "public"."obs_sbn"."rmscorr" IS 'ADES: Correlation between RA and Dec or between distance and position angle. This is derived from the covariance matrix, where the off-diagonal term is rmsCorr x rmsRA x rmsDec (for RA and Dec), and rmsCorr x rmsdist x rmspa (for dist and pa)';
COMMENT ON COLUMN "public"."obs_sbn"."delay" IS 'ADES: Observed radar time delay in seconds';
COMMENT ON COLUMN "public"."obs_sbn"."rmsdelay" IS 'ADES: Delay uncertainty in microseconds ';
COMMENT ON COLUMN "public"."obs_sbn"."doppler" IS 'ADES: Observed radar Doppler shift in Hz';
COMMENT ON COLUMN "public"."obs_sbn"."rmsdoppler" IS 'ADES: Doppler shift uncertainty in Hz';
COMMENT ON COLUMN "public"."obs_sbn"."astcat" IS 'ADES: Star catalog used for the astrometric reduction or, in case of occultation observations, for the occulted star (a list of accepted astcat values is availble at the following link https://minorplanetcenter.net/mpcops/documentation/valid-ades-values/#astCat)';
COMMENT ON COLUMN "public"."obs_sbn"."mag" IS 'ADES: Apparent magnitude in specified band';
COMMENT ON COLUMN "public"."obs_sbn"."rmsmag" IS 'ADES: Apparent magnitude uncertainty in magnitudes';
COMMENT ON COLUMN "public"."obs_sbn"."band" IS 'ADES: Passband designation for photometry (a list of accepted astcat values is availble at the following link https://minorplanetcenter.net/mpcops/documentation/valid-ades-values/#band)';
COMMENT ON COLUMN "public"."obs_sbn"."photcat" IS 'ADES: Star catalog used for the photometric reduction (a list of accepted astcat values is availble at the following link https://minorplanetcenter.net/mpcops/documentation/valid-ades-values/#astCat)';
COMMENT ON COLUMN "public"."obs_sbn"."photap" IS 'ADES: Photometric aperture radius in arcsec';
COMMENT ON COLUMN "public"."obs_sbn"."nucmag" IS 'ADES: Nuclear magnitude flag for comets, primarily used for archival data (photap should be used to communicate information in the new standard). 1=True for archival cometary nuclear magnitude measurements, 0=False otherwise. ';
COMMENT ON COLUMN "public"."obs_sbn"."logsnr" IS 'ADES: The log10 of the signal-to-noise ratio of the source in the image integrated on the entire aperture used for astrometric centroid';
COMMENT ON COLUMN "public"."obs_sbn"."seeing" IS 'ADES: Size of seeing disc in arcsec, measured at Full-Width, Half-Max of the target point spread function';
COMMENT ON COLUMN "public"."obs_sbn"."exp" IS 'ADES: Exposure time in seconds';
COMMENT ON COLUMN "public"."obs_sbn"."rmsfit" IS 'ADES: RMS of fit of astrometric comparison stars in arcsec';
COMMENT ON COLUMN "public"."obs_sbn"."com" IS 'ADES: Flag to indicate that the observation is reduced to the center of mass. Values are 1=True, 0=False. False implies a measurement to the peak power position';
COMMENT ON COLUMN "public"."obs_sbn"."frq" IS 'ADES: Carrier reference frequency in MHz';
COMMENT ON COLUMN "public"."obs_sbn"."disc" IS 'ADES: Discovery flag (more documentation needs to be added here).';
COMMENT ON COLUMN "public"."obs_sbn"."subfrm" IS 'ADES: Originally reported reference frame for angular measurements. The subfrm does not reflect the frame of the associated ADES observations, which are always J2000.0. For example, B1950.0 corresponds to the letter A in column 14 in the 80-column format';
COMMENT ON COLUMN "public"."obs_sbn"."subfmt" IS 'ADES: Format in which the observation was originally submitted to the MPC. This is filled by the MPC (a list of accepted astcat values is availble at the following link https://minorplanetcenter.net/mpcops/documentation/valid-ades-values/#subfmt)';
COMMENT ON COLUMN "public"."obs_sbn"."prectime" IS 'ADES: Precision in millionths of a day of the reported observation time for archival MPC1992 observations and earlier data';
COMMENT ON COLUMN "public"."obs_sbn"."precra" IS 'ADES: Precision for archival MPC1992 observations or earlier data in seconds for RA';
COMMENT ON COLUMN "public"."obs_sbn"."precdec" IS 'ADES: Precision for archival MPC1992 observations or earlier data in arcsec for Dec';
COMMENT ON COLUMN "public"."obs_sbn"."unctime" IS 'ADES: Estimated systematic time error in seconds. This field indicates a presumed level of systematic clock error. ';
COMMENT ON COLUMN "public"."obs_sbn"."notes" IS 'ADES: A set of one-character note flags to communicate observing circumstances (a list of accepted notes values is availble at the following link https://minorplanetcenter.net/mpcops/documentation/valid-ades-values/#notes';
COMMENT ON COLUMN "public"."obs_sbn"."remarks" IS 'ADES: A comment provided by the observer. ';
COMMENT ON COLUMN "public"."obs_sbn"."deprecated" IS 'ADES: Deprecated observation that is preserved for historical purpose. Do not use it in the orbit fitting. The only allowed value is X';
COMMENT ON COLUMN "public"."obs_sbn"."localuse" IS 'ADES: Container to hold subelements carrying ancillary information not envisioned by the standard';
COMMENT ON COLUMN "public"."obs_sbn"."nstars" IS 'ADES: Number of stars in the astrometric fit';
COMMENT ON COLUMN "public"."obs_sbn"."prev_desig" IS 'MPC_ops: Previous designation for a redesignated observations (see also the obs_alteration_redesignations table https://minorplanetcenter.net/mpcops/documentation/obs-alterations-redesignations/)';
COMMENT ON COLUMN "public"."obs_sbn"."prev_ref" IS 'MPC_ops: Previous publication references';
COMMENT ON COLUMN "public"."obs_sbn"."rmstime" IS 'ADES: Random uncertainty in time as estimated by the observer';
COMMENT ON COLUMN "public"."obs_sbn"."created_at" IS 'MPC_ops: Date and time of initial row insert';
COMMENT ON COLUMN "public"."obs_sbn"."updated_at" IS 'MPC_ops: Date and time of latest row update';
COMMENT ON COLUMN "public"."obs_sbn"."trkmpc" IS 'ADES: MPC-internal object identifier';
COMMENT ON COLUMN "public"."obs_sbn"."orbit_id" IS 'MPC_ops: Unique identifier for the orbit calculation. This field is not currently used';
COMMENT ON COLUMN "public"."obs_sbn"."designation_asterisk" IS 'MPC_ops: Equivalent of the asterisks used to mark initial tracklets for component provisional designations. One object can have multiple discovery_asterisks';
COMMENT ON COLUMN "public"."obs_sbn"."all_pub_ref" IS 'MPC_ops: Array of publication references that contained any information about the observation';
COMMENT ON COLUMN "public"."obs_sbn"."shapeocc" IS 'ADES: For occultation observations, a flag to indicate that the observation reduction assumes a shape-based plane-of-sky cross-section. Values are 1=True or 0=False that implies that a circular cross section was assumed';
COMMENT ON COLUMN "public"."obs_sbn"."obssubid" IS 'ADES: Observation identifier, optionally included by the observer in the submission, that is unique to a given observing program';
COMMENT ON COLUMN "public"."obs_sbn"."replacesobsid" IS 'MPC_ops: Observation identifier of the old published observations that has been replaced by this new observation. This field is not currently used. ';
COMMENT ON COLUMN "public"."obs_sbn"."group_id" IS 'MPC_ops: Observation group identifier used to group duplicate/near-duplicate observations. This field is not currently used';
COMMENT ON TABLE "public"."obs_sbn" IS 'Table used to record all the observations published by the MPC. Contains observations associated with designated objects and observations associated with the Isolated Tracklet File (ITF).';

-- ----------------------------
-- Indexes structure for table obs_sbn
-- ----------------------------
CREATE INDEX "obs_sbn_count_idx" ON "public"."obs_sbn" USING btree (
  (1) "pg_catalog"."int4_ops" ASC NULLS LAST
);
CREATE INDEX "obs_sbn_created_at_idx" ON "public"."obs_sbn" USING btree (
  "created_at" "pg_catalog"."timestamptz_ops" ASC NULLS LAST
);
CREATE INDEX "obs_sbn_submission_block_id_key" ON "public"."obs_sbn" USING btree (
  "submission_block_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) ;
CREATE INDEX "obs_sbn_trkid_idx" ON "public"."obs_sbn" USING btree (
  "trkid" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) ;
CREATE INDEX "obs_sbn_updated_at_idx" ON "public"."obs_sbn" USING btree (
  "updated_at" "pg_catalog"."timestamptz_ops" ASC NULLS LAST
) ;

-- ----------------------------
-- Primary Key structure for table obs_sbn
-- ----------------------------
ALTER TABLE "public"."obs_sbn" ADD CONSTRAINT "obs_sbn_pkey" PRIMARY KEY ("id");
