apiVersion: v1
kind: Service
metadata:
  labels:
    cnpg.io/cluster: mpc-sandbox-prod
  annotations:
    metallb.universe.tf/address-pool: sdf-services
  name: mpc-sandbox-loadbalancer
  namespace: mpc-sandbox-prod
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    postgresql: mpc-sandbox-prod
  sessionAffinity: None
  type: LoadBalancer
